import React, { useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { AlertTriangle, Bell, Building2, CalendarDays, ChevronDown, FileCheck2, LayoutDashboard, Menu, Package, Plus, Search, Truck, UserRound, Users, X } from 'lucide-react'
import './styles.css'

const people = [
  { name: 'Ahmet Yılmaz', role: 'Sayaç Okuma Personeli', company: 'Anadolu Enerji A.Ş.', region: 'Ankara / Çankaya', docs: '2 / 3', status: 'Aktif' },
  { name: 'Zeynep Kaya', role: 'Bölge Sorumlusu', company: 'Marmara Doğalgaz Ltd.', region: 'İstanbul / Kadıköy', docs: '3 / 3', status: 'Aktif' },
  { name: 'Mehmet Demir', role: 'Sayaç Okuma Personeli', company: 'Anadolu Enerji A.Ş.', region: 'Konya / Selçuklu', docs: '1 / 3', status: 'Belge Eksik' },
  { name: 'Elif Şahin', role: 'Saha Operasyon Uzmanı', company: 'Ege Sayaç Hizmetleri', region: 'İzmir / Bornova', docs: '3 / 3', status: 'Aktif' }
]
const menu = [['Genel Bakış', LayoutDashboard], ['Personeller', Users], ['Şirketler', Building2], ['Belgeler', FileCheck2], ['Depolar', Package], ['Araç Filosu', Truck]]

function App() {
  const [active, setActive] = useState('Genel Bakış')
  const [query, setQuery] = useState('')
  const [modal, setModal] = useState(false)
  const filtered = useMemo(() => people.filter(p => `${p.name} ${p.role} ${p.company}`.toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr'))), [query])
  return <div className="app">
    <aside className="sidebar"><div className="brand"><div className="brand-icon"><Users size={20}/></div><div><b>Personel<span>360</span></b><small>Yönetim Sistemi</small></div></div><div className="workspace"><Building2 size={16}/><div><small>Çalışma alanı</small><strong>Merkez Yönetim</strong></div><ChevronDown size={15}/></div><small className="nav-label">MENÜ</small>{menu.map(([label, Icon]) => <button className={`nav-item ${active === label ? 'active' : ''}`} onClick={() => setActive(label)} key={label}><Icon size={18}/>{label}{label === 'Belgeler' && <em>6</em>}</button>)}<div className="account"><div className="avatar dark">FA</div><div><b>Fatih Ayka</b><small>Sistem Yöneticisi</small></div></div></aside>
    <main><header><div className="breadcrumb">Yönetim <b>/</b> <strong>{active}</strong></div><div className="userbar"><button className="icon-btn"><Bell size={19}/><i>3</i></button><div className="avatar">FA</div><span>Fatih Ayka</span><ChevronDown size={15}/></div></header><section className="content"><div className="page-heading"><div><small className="eyebrow">PERŞEMBE, 24 EYLÜL 2026</small><h1>Genel Bakış</h1><p>Operasyonlarınızın güncel durumuna hızlıca göz atın.</p></div><button className="primary" onClick={() => setModal(true)}><Plus size={18}/> Yeni Personel</button></div><div className="stats"><Stat icon={Users} title="Toplam Personel" value="248" color="teal"/><Stat icon={UserRound} title="Aktif Personel" value="231" color="blue"/><Stat icon={AlertTriangle} title="Belge Uyarısı" value="6" color="orange"/><Stat icon={Truck} title="Aktif Araç" value="42" color="purple"/></div><div className="grid"><section className="card"><div className="card-heading"><div><h2>Son Eklenen Personeller</h2><p>Sisteme son eklenen personel kayıtları</p></div><button className="link-btn" onClick={() => setActive('Personeller')}>Tümünü Gör →</button></div><div className="tools"><div className="search"><Search size={16}/><input placeholder="Personel ara..." value={query} onChange={e => setQuery(e.target.value)}/></div><button className="filter">Tüm Durumlar <ChevronDown size={14}/></button></div><div className="table-wrap"><table><thead><tr><th>PERSONEL</th><th>ŞİRKET / GÖREV</th><th>BÖLGE</th><th>BELGELER</th><th>DURUM</th></tr></thead><tbody>{filtered.map(person => <tr key={person.name}><td><b>{person.name}</b></td><td><b>{person.company}</b><small>{person.role}</small></td><td>{person.region}</td><td className={person.docs === '3 / 3' ? 'success' : 'warning'}><FileCheck2 size={15}/> {person.docs}</td><td><span className={`status ${person.status === 'Aktif' ? 'success' : 'warning'}`}>● {person.status}</span></td></tr>)}</tbody></table>{!filtered.length && <div className="empty">Aramanızla eşleşen personel bulunamadı.</div>}</div></section><aside className="right-column"><section className="card"><div className="card-heading"><div><h2>Belge Uyarıları</h2><p>Aksiyon gerektiren belgeler</p></div><AlertTriangle className="warning" size={20}/></div><Alert name="Mehmet Demir" doc="MYK Belgesi" days="3 gün kaldı"/><Alert name="Ayşe Çelik" doc="Psikoteknik Belgesi" days="12 gün kaldı"/><Alert name="Burak Aydın" doc="SRC Belgesi" days="18 gün kaldı"/><button className="notice" onClick={() => setActive('Belgeler')}>Tüm uyarıları görüntüle</button></section><section className="card quick"><h2>Hızlı İşlemler</h2><button onClick={() => setModal(true)}><Plus size={16}/> Personel Ekle</button><button onClick={() => setActive('Belgeler')}><CalendarDays size={16}/> Belge Takvimi</button><button onClick={() => setActive('Depolar')}><Package size={16}/> Stok Hareketi</button></section></aside></div></section></main>
    {modal && <div className="overlay" onClick={() => setModal(false)}><div className="modal" onClick={e => e.stopPropagation()}><button className="close" onClick={() => setModal(false)}><X size={18}/></button><h2>Yeni Personel</h2><p>Personel kartı temel bilgilerini girin.</p><div className="form-grid"><label>Ad<input placeholder="Ad"/></label><label>Soyad<input placeholder="Soyad"/></label><label>Şirket<select><option>Şirket seçin</option><option>Anadolu Enerji A.Ş.</option><option>Marmara Doğalgaz Ltd.</option></select></label><label>Görev<input placeholder="Görev / unvan"/></label><label>Telefon<input placeholder="05xx xxx xx xx"/></label><label>İşe giriş tarihi<input type="date"/></label><label className="full">MYK belgesi son geçerlilik tarihi<input type="date"/></label><label className="full">SRC / Psikoteknik bilgisi<textarea placeholder="Belge numarası veya açıklama"/></label></div><div className="modal-actions"><button className="cancel" onClick={() => setModal(false)}>Vazgeç</button><button className="primary" onClick={() => setModal(false)}>Personeli Kaydet</button></div></div></div>}
  </div>
}
function Stat({icon: Icon, title, value, color}) { return <div className="stat"><div className={`stat-icon ${color}`}><Icon size={19}/></div><div><small>{title}</small><strong>{value}</strong><span>Güncel kayıt</span></div></div> }
function Alert({name, doc, days}) { return <div className="alert"><div className="alert-icon"><AlertTriangle size={15}/></div><div><b>{name}</b><small>{doc}</small></div><span>{days}</span></div> }
createRoot(document.getElementById('root')).render(<App />)
